<a href="https://colab.research.google.com/github/Raudhil/Machine-Learning-2025/blob/main/Jobsheet%2013/RAUDHIL_FIRDAUS_NAUFAL_JS13_Praktikum3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Praktikum 1**

**Langkah:**

Buat dataset sederhana (XOR).

Inisialisasi bobot dan bias.

Implementasikan forward pass.

Hitung error dan lakukan backpropagation.

Update bobot menggunakan gradient descent.

In [ ]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.2540418689873392
Epoch 1000, Loss: 0.2489254088154776
Epoch 2000, Loss: 0.23535178772453808
Epoch 3000, Loss: 0.18195854197618286
Epoch 4000, Loss: 0.15147045564123343
Epoch 5000, Loss: 0.13993153803281277
Epoch 6000, Loss: 0.1348854364974286
Epoch 7000, Loss: 0.13221768204053658
Epoch 8000, Loss: 0.13060702516584713
Epoch 9000, Loss: 0.12954345910055642
Prediksi:
[[0.04847747]
 [0.50001619]
 [0.93245302]
 [0.50822002]]


**Tugas 1**


Ubah jumlah neuron hidden layer menjadi 3.

In [ ]:
# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.2822343450251595
Epoch 1000, Loss: 0.24998175281374235
Epoch 2000, Loss: 0.24846388663387
Epoch 3000, Loss: 0.2325788958924659
Epoch 4000, Loss: 0.10203055464812211
Epoch 5000, Loss: 0.021941342678303277
Epoch 6000, Loss: 0.009735466937629689
Epoch 7000, Loss: 0.0059380428412692645
Epoch 8000, Loss: 0.004190087796248304
Epoch 9000, Loss: 0.0032069833036875483
Prediksi:
[[0.03020431]
 [0.94855612]
 [0.94878151]
 [0.06445946]]


Bandingkan hasil loss dengan konfigurasi awal.



Berdasarkan hasil loss antara konfigurasi awal dengan konfigurasi baru yang menambahkan hidden neuron sebanyak 1, terlihat kalau loss turun hingga 0.0025, walaupun itu kecil, tapi bisa diketahui kalau menambah neuron dapat membantu menurunkan error.

Tambahkan fungsi aktivasi ReLU dan bandingkan hasil.



In [ ]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Hyperparams
input_size = 2
hidden_size = 3
output_size = 1
lr = 0.1
epochs = 10000
np.random.seed(42)

# initialize once and copy to ensure fair comparison
W1_init = np.random.randn(input_size, hidden_size)
b1_init = np.zeros((1, hidden_size))
W2_init = np.random.randn(hidden_size, output_size)
b2_init = np.zeros((1, output_size))

# Aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(a):
    return a * (1 - a)

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

# Train with sigmoid hidden
W1 = W1_init.copy(); b1 = b1_init.copy(); W2 = W2_init.copy(); b2 = b2_init.copy()
for epoch in range(epochs):
    z1 = X.dot(W1) + b1
    a1 = sigmoid(z1)
    z2 = a1.dot(W2) + b2
    a2 = sigmoid(z2)

    error = y - a2
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = a1.T.dot(d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = d_a2.dot(W2.T) * sigmoid_derivative(a1)
    d_W1 = X.T.dot(d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    W1 += lr * d_W1; b1 += lr * d_b1
    W2 += lr * d_W2; b2 += lr * d_b2

sigmoid_loss = np.mean(np.square(y - a2))
sigmoid_pred = a2.copy()

# Train with ReLU hidden (same init)
W1 = W1_init.copy(); b1 = b1_init.copy(); W2 = W2_init.copy(); b2 = b2_init.copy()
for epoch in range(epochs):
    z1 = X.dot(W1) + b1
    a1 = relu(z1)
    z2 = a1.dot(W2) + b2
    a2 = sigmoid(z2)

    error = y - a2
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = a1.T.dot(d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = d_a2.dot(W2.T) * relu_derivative(z1)
    d_W1 = X.T.dot(d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    W1 += lr * d_W1; b1 += lr * d_b1
    W2 += lr * d_W2; b2 += lr * d_b2

relu_loss = np.mean(np.square(y - a2))
relu_pred = a2.copy()

print("Sigmoid hidden final loss:", sigmoid_loss)
print("Sigmoid hidden predictions:\n", np.round(sigmoid_pred, 3))
print("ReLU hidden final loss:", relu_loss)
print("ReLU hidden predictions:\n", np.round(relu_pred, 3))
# ...existing code...

Sigmoid hidden final loss: 0.0022974157268842183
Sigmoid hidden predictions:
 [[0.025]
 [0.953]
 [0.951]
 [0.063]]
ReLU hidden final loss: 0.00035154169220683637
ReLU hidden predictions:
 [[0.03 ]
 [0.986]
 [0.986]
 [0.012]]
